# Generated by Django 5.1.7 on 2025-06-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='rigs', to='core.component'),
        ),
    ]
