# Generated by Django 5.1.7 on 2025-03-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='model',
            new_name='name',
        ),
    ]
