# Generated by Django 5.1.7 on 2025-07-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rig_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='openings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='packs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
