# Generated by Django 5.1.7 on 2025-07-10 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_component_openings_component_packs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rigging',
            name='type_rigging',
            field=models.CharField(choices=[('I+R', 'Inspection + Repack'), ('Reparation', 'Reparation'), ('Fabrication', 'Fabrication')], default='I+R', max_length=20),
        ),
        migrations.RemoveField(
            model_name='rigging',
            name='serial_numbers',
        ),
        migrations.AddField(
            model_name='rigging',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rigging',
            name='component',
            field=models.ForeignKey(help_text='Component involved in this rigging', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riggings', to='core.component'),
        ),
        migrations.AlterField(
            model_name='rigging',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rigging',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the work done', null=True),
        ),
        migrations.AlterField(
            model_name='rigging',
            name='rig',
            field=models.ForeignKey(blank=True, help_text='Rig associated with this rigging', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riggings', to='core.rig'),
        ),
        migrations.AlterField(
            model_name='rigging',
            name='rigger',
            field=models.ForeignKey(blank=True, help_text='Rigger assigned to this work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riggings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RiggingType',
        ),
    ]
