# Generated by Django 5.1.7 on 2025-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rigging_type_rigging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='usage_type',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Tandem', 'Tandem'), ('Emergency', 'Emergency')], default='Sport', max_length=20),
        ),
    ]
