# Generated by Django 5.1.7 on 2025-07-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_component_usage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('line_type', models.CharField(max_length=50)),
                ('jumps', models.IntegerField(default=0)),
                ('aad_jumps_on_mount', models.IntegerField(blank=True, null=True)),
                ('killline_jumps_on_mount', models.IntegerField(blank=True, null=True)),
                ('kill_line_jumps', models.IntegerField(default=0)),
                ('canopy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drogues', to='core.component')),
            ],
        ),
        migrations.CreateModel(
            name='Lineset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('line_type', models.CharField(max_length=50)),
                ('jumps', models.IntegerField(default=0)),
                ('aad_jumps_on_mount', models.IntegerField(blank=True, null=True)),
                ('canopy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linesets', to='core.component')),
            ],
        ),
    ]
