# Generated by Django 5.1.7 on 2025-07-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_drogue_lineset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drogue',
            old_name='canopy',
            new_name='container',
        ),
    ]
